"""add habits

Revision ID: 4b8ada3e247f
Revises: d4c1c23768e2
Create Date: 2026-03-28 00:36:21.602643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '4b8ada3e247f'
down_revision: Union[str, Sequence[str], None] = 'd4c1c23768e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('cadence', sa.String(length=10), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_user_id'), ['user_id'], unique=False)

    op.create_table('habit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uq_habit_entry_date')
    )
    with op.batch_alter_table('habit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_entries_habit_id'), ['habit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_entries_habit_id'))

    op.drop_table('habit_entries')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_user_id'))

    op.drop_table('habits')
    # ### end Alembic commands ###
