"""add theme preference

Revision ID: 540b80fae260
Revises: 06b17f936a3f
Create Date: 2026-03-27 23:58:59.714681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b80fae260'
down_revision: Union[str, Sequence[str], None] = '06b17f936a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=10), nullable=False, server_default='dark'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
